[package]
name = "yew-example-crate"
version = "0.1.0"
edition = "2021"


[dependencies]
console_error_panic_hook = "0.1"
wasm-bindgen = "0.2"
ybc = "0.2"
yew = "0.18"
example_search = { path = "./example-search", features = [] }


[workspace]
members = []
